#!/bin/bash
#
# Code generated by cmdcomp "$CMDCOMP_VERSION". DO NOT EDIT.
# For more information about cmdcomp, please refer to https://github.com/yassun7010/cmdcomp .
#

_mycli() {
  local word cmd opts cur cmd_cur opts_cur
  COMPREPLY=()
  cmd=""
  opts=""
  cur=0
  cmd_cur=0
  opts_cur=0

  for word in ${COMP_WORDS[@]}; do
    case "${cmd},${word}" in
      ",$1")
        cmd="_mycli"
        cur=$(( cur + opts_cur + 1 ))
        ;;

      _mycli,gcloud)
        cmd="_mycli_gcloud"
        cur=$(( cur + opts_cur + 1 ))
        ;;

      _mycli,gcs)
        cmd="_mycli_gcs"
        cur=$(( cur + opts_cur + 1 ))
        ;;

      _mycli,composer-operation)
        cmd="_mycli_composer_operation"
        cur=$(( cur + opts_cur + 1 ))
        ;;

      _mycli,git)
        cmd="_mycli_git"
        cur=$(( cur + opts_cur + 1 ))
        ;;

      _mycli,test)
        cmd="_mycli_test"
        cur=$(( cur + opts_cur + 1 ))
        ;;

      _mycli_test,rubocop)
        cmd="_mycli_test_rubocop"
        cur=$(( cur + opts_cur + 1 ))
        ;;

      _mycli_test,pytest)
        cmd="_mycli_test_pytest"
        cur=$(( cur + opts_cur + 1 ))
        ;;

      *)
        opts_cur=$(( opts_cur + 1 ))
        ;;
    esac
  done

  case "${cmd}" in
    _mycli)
      cmd_cur=$cur
      while [ $cur -lt $COMP_CWORD ] ; do
        cur=$(( cur + 1 ))
        case "${COMP_WORDS[cur-1]}" in
          --verbose)
            cmd_cur=$(( cmd_cur + 1 ))
            ;;

          --help)
            cmd_cur=$(( cmd_cur + 1 ))
            ;;

          *)
            break
            ;;
        esac
      done

      if [[ ${COMP_WORDS[COMP_CWORD]} == -* ]] ; then
        opts="--verbose --help"
        COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )
        return 0
      elif [ $cur -eq $COMP_CWORD ] ; then
        opts="gcloud gcs composer-operation git test"
        COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )
        return 0
      fi

      return 0
      ;;

    _mycli_gcloud)
      cmd_cur=$cur
      while [ $cur -lt $COMP_CWORD ] ; do
        cur=$(( cur + 1 ))
      done

      opts=""
      COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )

      return 0
      ;;

    _mycli_gcs)
      cmd_cur=$cur
      while [ $cur -lt $COMP_CWORD ] ; do
        cur=$(( cur + 1 ))
      done

      opts=""
      COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )

      return 0
      ;;

    _mycli_composer_operation)
      cmd_cur=$cur
      while [ $cur -lt $COMP_CWORD ] ; do
        cur=$(( cur + 1 ))
      done

      opts=""
      COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )

      return 0
      ;;

    _mycli_git)
      cmd_cur=$cur
      while [ $cur -lt $COMP_CWORD ] ; do
        cur=$(( cur + 1 ))
      done

      opts=""
      COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )

      return 0
      ;;

    _mycli_test)
      cmd_cur=$cur
      while [ $cur -lt $COMP_CWORD ] ; do
        cur=$(( cur + 1 ))
      done

      if [[ ${COMP_WORDS[COMP_CWORD]} == -* ]] ; then
        opts=""
        COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )
        return 0
      elif [ $cur -eq $COMP_CWORD ] ; then
        opts="rubocop pytest"
        COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )
        return 0
      fi

      return 0
      ;;

    _mycli_test_rubocop)
      cmd_cur=$cur
      while [ $cur -lt $COMP_CWORD ] ; do
        cur=$(( cur + 1 ))
        case "${COMP_WORDS[cur-1]}" in
          --auto-correct|-A)
            cmd_cur=$(( cmd_cur + 1 ))
            ;;

          *)
            break
            ;;
        esac
      done

      opts="--auto-correct -A"
      COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )

      return 0
      ;;

    _mycli_test_pytest)
      cmd_cur=$cur
      while [ $cur -lt $COMP_CWORD ] ; do
        cur=$(( cur + 1 ))
      done

      opts=""
      COMPREPLY=( $(compgen -W "${opts}" -- "${COMP_WORDS[COMP_CWORD]}") )

      return 0
      ;;

  esac
}

complete -F _mycli -o bashdefault -o default mycli
